### ISSUE TITLE
Improve the narrative 

### ISSUE THREAD

**Issue by Nikoleta-v3** [Nikoleta-v3/bibliometric-study-of-the-prisoners-dilemma#100]
Reviewer 1
> In addition, the authors should specify clearly the significance of their study, what specific implications can be obtained from their analyses, particularly those concerning future research directions. As one of the typical aims for review paper is to analyze the previous studies in order to provide helpful suggestions or directions for researches to conduct future studies. This should have been done in the Discussion and Conclusion sections. The authors need to summarize their findings instead of presenting and discussing individual findings. More importantly, they need to inspire the readers by providing a list of suggestions/directions of future research based on the discussion. The authors need to advise readers what to do next rather than ask the readers to interpret the data on their own. 

**Reviewer 2** These can/will be broken down to more issues

Suggested improvements 

- [ ]  I suggest mapping your data collection in a flow chart. 
- [ ] The strength of ties could be analyzed to map multiple collaborations between two nodes. 
- [ ] The contribution of the paper should be named in the introduction. 
- [ ] I suggest only analyzing the centrality measures and structure of the co-author network (result section) and discussing what this could mean based on the previous literature (conclusion section). I would avoid claiming that benefits were tested in this paper. 
- [ ] Disciplines differ a lot in the number of co-authors. For example, medical papers often have more than 5 co-authors where sociology papers often have single authors. Isn't the results merely coming from this pre-established difference between disciplines? 

- [ ] The structure of the text needs to be improved a lot before this work is publishable. The methodology should be outlined in the Methodology section and not in the Results section (e.g. fitting exponential lines to the number of articles to see that the numbers are increasing). The contribution of the paper needs to be in the introduction and not in the last paragraph of the Methodology section. 
- [ ] The text contains some grammar mistakes (e.g. “The performance of the models are”) typos (e.g. “Figure ??”) and unclear reference (e.g. “In comparison, 2b gives the visualisation of LDA” where 2b could refer to a Table, Figure, or topic). 
- [ ] The abbreviation should be spelt out the first time they are used and then the short version should be used consequently. 
- [ ] I like that Latent Dirichlet Allocation is defined in the introduction. But it would enhance the readability if it was defined the first time it is used. 
- [ ] The author said that “The appropriate number of topics is chosen based on the coherence value”. 6 topics provided the best coherence value but still 5 topics were selected. The description of this conduct is a bit confusing. 
- [ ] Reference to software should go to the method section instead of the Acknowledgment.

**Comment by drvinceknight** [comment]
> * Isn't the results merely coming from this pre-established difference between disciplines?

We aim to discuss relative comparisons and not absolute. So within the field of game theory ...
