### ISSUE TITLE
Justify the reasons behind the selected keywords

### ISSUE THREAD

**Issue by Nikoleta-v3** [Nikoleta-v3/bibliometric-study-of-the-prisoners-dilemma#96]
> First, the authors used search terms “prisoner's dilemma", “prisoners dilemma", “prisoner dilemma", “prisoners evolution", and “prisoner game theory" to collect data. However, they did not justify the reasons for the use of these terms. Why these terms, is there any support for the choice?

**Comment by Nikoleta-v3** [comment]
we looked at a number of paper that we know are relevant and identified that these are the relevant keywords/

**Comment by drvinceknight** [comment]
> Other terms such as donation game, etc could also have been used but were not.

**Comment by drvinceknight** [comment]
> Whilst the results obtained, do generalise to the overall stated goal of the paper they are inferred only from the dataset used which is available at...
